export const Actions = {
    USER_LOGIN: 'LOGIN',
    USER_SUCCESS_LOGIN:'USER_SUCCESS_LOGIN',
    USER_LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    SOCKET_FETCHING: 'SOCKET_FETCHING',
    CHAT_ID_FETCHING: 'CHAT_ID_FETCHING',
    CHAT_MESSAGE_GET: 'CHAT_MESSAGE_GET',
    CHAT_MESSAGE_SUCCESS_GET: 'CHAT_MESSAGE_SUCCESS_GET',
    CHAT_MESSAGE_FAIL_GET: 'CHAT_MESSAGE_FAIL_GET',
    MESSAGE_FETCHING: 'MESSAGE_FETCHING',
    CONVERSATION_LIST_FETCHING:'CONVERSATION_LIST_FETCHING',
    CREATED_CONVERSATION_FETCHING: 'CREATED_CONVERSATION_FETCHING'
}